const data = {
    products: [

          {
            name: 'Beaver Sus',
            slug: 'Beaver-sus',
            image: '/images/beaver sus.jpg',
            price: 14.99,
            countInStock: 10,
            brand: 'guy',
            rating: 5.0,
            numReviews: 10,
            description: 'sticker',
        },
          {
            name: 'Canadian Booty',
            slug: 'Canadian-Booty',
            image: '/images/canadian booty.jpg',
            price: 14.99,
            countInStock: 10,
            brand: 'guy',
            rating: 5.0,
            numReviews: 10,
            description: 'sticker',
        },
          {
            name: 'Fishing',
            slug: 'Fishing',
            image: '/images/fishing.jpg',
            price: 14.99,
            countInStock: 10,
            brand: 'guy',
            rating: 5.0,
            numReviews: 10,
            description: 'sticker',
        },
          {
            name: 'guy heart',
            slug: 'guy-heart',
            image: '/images/guy heart.jpg',
            price: 14.99,
            countInStock: 10,
            brand: 'guy',
            rating: 5.0,
            numReviews: 10,
            description: 'sticker',
        },

          {
            name: "guy's masterpiece in color",
            slug: "guy's-masterpiece-in-color",
            image: '/images/guy-s masterpiece in color.jpg',
            price: 14.99,
            countInStock: 10,
            brand: 'guy',
            rating: 5.0,
            numReviews: 10,
            description: 'sticker',
        },
          {
            name: "Guy's Masterpiece",
            slug: "guy's-masterpiece",
            image: '/images/guy-s masterpiece.jpg',
            price: 14.99,
            countInStock: 10,
            brand: 'guy',
            rating: 5.0,
            numReviews: 10,
            description: 'sticker',
        },
          {
            name: 'guys rainbow',
            slug: 'guys-rainbow',
            image: '/images/guys-rainbow.jpg',
            price: 14.99,
            countInStock: 10,
            brand: 'guy',
            rating: 5.0,
            numReviews: 10,
            description: 'sticker',
        },
                {
            name: "Kevin",
            slug: 'kevin',
            image: '/images/kevin.jpg',
            price: 14.99,
            countInStock: 10,
            brand: 'guy',
            rating: 5.0,
            numReviews: 10,
            description: 'sticker',
        },
    ]
};
export default data;
